routes/admin.php
<?php

use Illuminate\Routing\Router;

/*
|--------------------------------------------------------------------------
| Front Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application frontend.
| These routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/** @var Router $routes */

$routes->get(
    '/',
    function () {
        return redirect(route('admin.dashboard'));
    }
)->name('index');

$routes->get('/dashboard', 'Dashboard\DashboardController@index')->name('dashboard');
$routes->get('/profile', 'Users\UsersController@profile')->name('users.profile');
$routes->get('/profile/edit', 'Users\UsersController@editProfile')->name('users.profile.edit');

$this->patch('/change-password', 'Users\UsersController@changePassword')->name('users.changePassword');
$routes->get('users/{status}/data-table', 'Users\UsersController@getPaginatedUsers')->name('users.table');
$routes->patch('users/{user}/status/{change}', 'Users\UsersController@changeStatus')->name('users.change.status');
$routes->resource('users', 'Users\UsersController');

$routes->get('roles/data-table', 'Users\RolesController@getPaginatedRoles')->name('roles.table');
$routes->resource('roles', 'Users\RolesController');

$routes->get('parties/data-table', 'Users\PartyController@getPaginatedParties')->name('parties.table');
$routes->resource('parties', 'Users\PartyController');

$routes->get('invoices/data-table', 'Invoice\InvoiceController@getPaginatedInvoices')->name('invoices.table');
$routes->resource('invoices', 'Invoice\InvoiceController');


$routes->get('customs/data-table', 'Custom\CustomController@getPaginatedCustoms')->name('customs.table');
$routes->resource('customs', 'Custom\CustomController');

$routes->get('permissions/data-table', 'Users\Permissions\PermissionsController@getPaginatedPermissions')->name('permissions.table');
$routes->get('/permissions/manage', 'Users\Permissions\PermissionsController@showRolesAndPermissions')->name('permissions.manage');
$routes->get('/permissions/{permission}/role/{role}/toggle', 'Users\Permissions\PermissionsController@togglePermission')->name('permissions.toggle');
$routes->resource('/permissions', 'Users\Permissions\PermissionsController');

resources/views/admin/modules/custom/create.blade.php
@extends('admin.layouts.main')

@section('title', 'Customs')

@section('breadcrumb')
  <li class="m-nav__item">
    <a href="{{ route('admin.customs.index') }}" class="m-nav__link">
      <span class="m-nav__link-text">Customs</span>
    </a>
  </li>
  <li class="m-nav__separator">
    -
  </li>
  <li class="m-nav__item">
    <a href="#" class="m-nav__link">
      <span class="m-nav__link-text">Create</span>
    </a>
  </li>
@endsection

@section('content')
  {{--send further props from this create user component--}}
  <custom-form inline-template
                allinvoices="{{ json_encode($invoices) }}"
                allparties="{{ json_encode($parties) }}"
                url="{{ route('admin.customs.store') }}">
    <portlet-content header="Custom" subheader="Create" isForm="true">
      <template slot="body">
        @include('admin.modules.custom.partials.form')
      </template>
    </portlet-content>
  </custom-form>
@endsection

resources/views/admin/modules/custom/edit.blade.php
@extends('admin.layouts.main')

@section('title', 'Customs')

@section('breadcrumb')
  <li class="m-nav__item">
    <a href="{{ route('admin.customs.index') }}" class="m-nav__link">
      <span class="m-nav__link-text">Customs</span>
    </a>
  </li>
  <li class="m-nav__separator">
    -
  </li>
  <li class="m-nav__item">
    <a href="#" class="m-nav__link">
      <span class="m-nav__link-text">Edit</span>
    </a>
  </li>
@endsection

@section('content')
  {{--send further props from this create user component--}}
  <custom-form inline-template url="{{ route('admin.customs.update', $custom->id) }}" method="patch"
               allinvoices="{{ json_encode($invoices) }}"
               allparties="{{ json_encode($parties) }}"
               custom="{{ json_encode($custom) }}">
    <portlet-content header="Custom" subheader="Edit" isForm="true">
      <template slot="body">
       @include('admin.modules.custom.partials.form')
      </template>
    </portlet-content>
  </custom-form>
@endsection

resources/views/admin/modules/custom/index.blade.php
@extends('admin.layouts.main')

@section('title', 'Customs')

@section('breadcrumb')
  <li class="m-nav__item">
    <a href="" class="m-nav__link">
      <span class="m-nav__link-text">Customs</span>
    </a>
  </li>
@endsection

@section('content')
  <portlet-content header="Customs" subheader="list">
    <template slot="action_button">
      <a href="{{ route('admin.customs.create') }}">
        <button
            class="btn btn-outline-info m-btn m-btn--icon m-btn--icon-only m-btn--custom m-btn--pill m-btn--air"
            title="Add new custtom"
            data-toggle="tooltip"
        >
          <i class="fa fa-plus"></i>
        </button>
      </a>
    </template>
    <template slot="body">
      <div class="row">
        <div class="col-md-12">
          <vue-table
              source="{{ route('admin.customs.table') }}"
              :columns="['custom_ref_no', 'vehicle_no', 'custom_amount', 'clearance_date', 'action']"
          ></vue-table>
        </div>
      </div>
    </template>
  </portlet-content>
@endsection

resources/views/admin/modules/custom/show.blade.php
@extends('admin.layouts.main')

@section('title', 'Customs')

@section('breadcrumb')
  <li class="m-nav__item">
    <a href="{{ route('admin.customs.index') }}" class="m-nav__link">
      <span class="m-nav__link-text">Customs</span>
    </a>
  </li>
  <li class="m-nav__separator">
    -
  </li>
  <li class="m-nav__item">
    <a href="{{ route('admin.customs.show', $custom->id) }}" class="m-nav__link">
      <span class="m-nav__link-text">{{ $custom->custom_ref_no }}</span>
    </a>
  </li>
@endsection

@section('content')
  <portlet-content header="Custom" subheader="Details">
    <template slot="action_button">
      <edit-button
          url="{{ route('admin.customs.edit', $custom->id) }}"
          title="Edit custom Details"
      >
      </edit-button>
    </template>
    <template slot="body">
      <div class="row">
        <div class="col-md-12">
          <table class="table">
            <tr>
              <td class="label"><strong> Custom Ref No. </strong></td>
              <td> {{ $custom->custom_ref_no }}</td>
            </tr>
            <tr>
              <td><strong> Vehicle No. </strong></td>
              <td> {{ $custom->vehicle_no ?? 'Not Available' }}</td>
            </tr>
            <tr>
              <td><strong> Invoices </strong></td>
              <td>
                @forelse($custom->invoices as $invoice)
                  <span class="m-badge m-badge--info" style="min-height:7px; min-width:7px;"></span>
                  <a href="{{ route('admin.invoices.show', $invoice->id) }}" title="View invoice details">
                    {{ $invoice->invoice_number }} &nbsp;
                  </a>

                @empty
                  Not Available
                @endforelse
              </td>
            </tr>
            <tr>
              <td><strong> Parties </strong></td>
              <td>
                @forelse($custom->parties as $party)
                  <span class="m-badge m-badge--info" style="min-height:7px; min-width:7px;"></span>
                  <a href="{{ route('admin.parties.show', $party->id) }}" title="View Party's Details">
                    {{ $party->name }} &nbsp;
                  </a>
                @empty
                  Not Available
                @endforelse
              </td>
            </tr>
            <tr>
              <td><strong> Quality </strong></td>
              <td> {{ $custom->quality ?? "Not Available" }}</td>
            </tr>
            <tr>
              <td><strong> Custom Amount </strong></td>
              <td> {{ $custom->custom_amoount ?? "Not Available" }}</td>
            </tr>
            <tr>
              <td><strong> VAT Amount </strong></td>
              <td> {{ $custom->vat_amount ?? "Not Available" }}</td>
            </tr>
            <tr>
              <td><strong> Clearance Charge </strong></td>
              <td> {{ $custom->clearance_charge ?? "Not Available" }}</td>
            </tr>
            <tr>
              <td><strong> Clearance Date </strong></td>
              <td> {{ $custom->formatted_clearance_date }}</td>
            </tr>
            <tr>
              <td><strong> Bale Quantity </strong></td>
              <td> {{ $custom->bale_quantity ?? "Not Available" }}</td>
            </tr>
          </table>
        </div>
      </div>
    </template>
  </portlet-content>
@endsection

resources/views/admin/modules/dashboard/index.blade.php
@extends('admin.layouts.main')

@section('title', 'Dashboard')

@section('breadcrumb')
  <li class="m-nav__item">
    <a href="" class="m-nav__link">
      <span class="m-nav__link-text">Dashboard</span>
    </a>
  </li>
@endsection

@section('content')
  <div class="m-portlet m-portlet--tab">
    <div class="m-portlet__head">
      <div class="m-portlet__head-caption">
        <div class="m-portlet__head-title">
          <span class="m-portlet__head-icon m--hide"><i class="la la-gear"></i></span>
          <h3 class="m-portlet__head-text">Welcome {{ currentUser()->formatted_full_name }}</h3>
        </div>
      </div>
    </div>

    <div class="m-portlet__body">

      <div class="m-section">
        <div class="m-section__content">
          <div class="m-demo" data-code-preview="true" data-code-html="true" data-code-js="false">
            <div class="m-demo__preview">
              <div class="row">
                <h6 class="text-center"> This is your dashboard</h6>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/admin/modules/party/create.blade.php
@extends('admin.layouts.main')

@section('title', 'Clients')

@section('breadcrumb')
    <li class="m-nav__item">
        <a href="{{ route('admin.parties.index') }}" class="m-nav__link">
            <span class="m-nav__link-text">Clients</span>
        </a>
    </li>
    <li class="m-nav__separator">
        -
    </li>
    <li class="m-nav__item">
        <a href="#" class="m-nav__link">
            <span class="m-nav__link-text">Create</span>
        </a>
    </li>
@endsection

@section('content')
    {{--send further props from this create user component--}}
    <party-form inline-template url="{{ route('admin.parties.store') }}">
        <portlet-content header="Client" subheader="Create" isForm="true">
            <template slot="body">
                @include('admin.modules.party.partials.form')
            </template>
        </portlet-content>
    </party-form>
@endsection

resources/views/admin/modules/party/edit.blade.php
@extends('admin.layouts.main')

@section('title', 'Clients')

@section('breadcrumb')
  <li class="m-nav__item">
    <a href="{{ route('admin.parties.index') }}" class="m-nav__link">
      <span class="m-nav__link-text">Parties</span>
    </a>
  </li>
  <li class="m-nav__separator">
    -
  </li>
  <li class="m-nav__item">
    <a href="#" class="m-nav__link">
      <span class="m-nav__link-text">Edit</span>
    </a>
  </li>
@endsection

@section('content')
  {{--send further props from this create user component--}}
  <party-form inline-template url="{{ route('admin.parties.update', $party->id) }}" method="patch"
               party="{{ json_encode($party) }}">
    <portlet-content header="Client" subheader="Edit" isForm="true">
      <template slot="body">
       @include('admin.modules.party.partials.form')
      </template>
    </portlet-content>
  </party-form>
@endsection

resources/views/admin/modules/party/index.blade.php
@extends('admin.layouts.main')

@section('title', 'Clients')

@section('breadcrumb')
  <li class="m-nav__item">
    <a href="" class="m-nav__link">
      <span class="m-nav__link-text">Clients</span>
    </a>
  </li>
@endsection

@section('content')
  <portlet-content header="Clients" subheader="list">
    <template slot="action_button">
      <a href="{{ route('admin.parties.create') }}">
        <button
            class="btn btn-outline-info m-btn m-btn--icon m-btn--icon-only m-btn--custom m-btn--pill m-btn--air"
            title="Add new client"
            data-toggle="tooltip"
        >
          <i class="fa fa-plus"></i>
        </button>
      </a>
    </template>
    <template slot="body">
      <div class="row">
        <div class="col-md-12">
          <vue-table
              source="{{ route('admin.parties.table') }}"
              :columns="['name', 'address', 'mobile', 'contact_person', 'action']"
          ></vue-table>
        </div>
      </div>
    </template>
  </portlet-content>
@endsection

resources/views/admin/modules/party/show.blade.php
@extends('admin.layouts.main')

@section('title', 'Clients')

@section('breadcrumb')
  <li class="m-nav__item">
    <a href="{{ route('admin.parties.index') }}" class="m-nav__link">
      <span class="m-nav__link-text">Clients</span>
    </a>
  </li>
  <li class="m-nav__separator">
    -
  </li>
  <li class="m-nav__item">
    <a href="{{ route('admin.parties.show', $party->id) }}" class="m-nav__link">
      <span class="m-nav__link-text">{{ $party->name }}</span>
    </a>
  </li>
@endsection

@section('content')
  <portlet-content header="Client" subheader="Details">
    <template slot="action_button">
      <edit-button
          url="{{ route('admin.parties.edit', $party->id) }}"
          title="Edit Party Details"
      >
      </edit-button>
    </template>
    <template slot="body">
      <div class="row">
        <div class="col-md-12">
          <table class="table">
            <tr>
              <td><strong> Name </strong></td>
              <td> {{ $party->name }}</td>
            </tr>
            <tr>
              <td><strong> Address </strong></td>
              <td>{{ $party->formatted_address }}</td>
            </tr>
            <tr>
              <td><strong> Phone </strong></td>
              <td>{{ $party->phone ?? "N/A" }}</td>
            </tr>
            <tr>
              <td><strong>Mobile</strong></td>
              <td>{{ $party->mobile or "N/A" }}</td>
            </tr>
            <tr>
              <td><strong>Contact Person</strong></td>
              <td>{{ $party->contact_person or "N/A" }}</td>
            </tr>
            <tr>
              <td><strong>Bank Name</strong></td>
              <td>{{ $party->bank or "N/A" }}</td>
            </tr>
            <tr>
              <td><strong>Contact Person</strong></td>
              <td>{{ $party->contact_person or "N/A" }}</td>
            </tr>
            <tr>
              <td><strong>Bank Name</strong></td>
              <td>{{ $party->bank or "N/A" }}</td>
            </tr>
            <tr>
              <td><strong>Account Number</strong></td>
              <td>{{ $party->bank_account or "N/A" }}</td>
            </tr>
            <tr>
              <td><strong>Contact Person</strong></td>
              <td>{{ $party->contact_person or "N/A" }}</td>
            </tr>
            <tr>
              <td><strong>IFSC Code</strong></td>
              <td>{{ $party->ifsc_code or "N/A" }}</td>
            </tr>
            <tr>
              <td><strong>Bank Area</strong></td>
              <td>{{ $party->bank_area or "N/A" }}</td>
            </tr>
            <tr>
              <td><strong>GST Number</strong></td>
              <td>{{ $party->gst_number or "N/A" }}</td>
            </tr>
            <tr>
              <td><strong>PAN</strong></td>
              <td>{{ $party->pan or "N/A" }}</td>
            </tr>
            <tr>
              <td><strong>IEC Number</strong></td>
              <td>{{ $party->iec_number or "N/A" }}</td>
            </tr>
            <tr>
              <td><strong>CIN Number</strong></td>
              <td>{{ $party->cin_number or "N/A" }}</td>
            </tr>
            <tr>
              <td><strong>LUT</strong></td>
              <td>{{ $party->lut or "N/A" }}</td>
            </tr>
            <tr>
              <td><strong>Other Details</strong></td>
              <td>{{ $party->other_details or "N/A" }}</td>
            </tr>
          </table>
        </div>
      </div>
    </template>
  </portlet-content>
@endsection

resources/views/admin/modules/permission/create.blade.php
@extends('admin.layouts.main')

@section('title', 'Modules')

@section('breadcrumb')
  <li class="m-nav__item">
    <a href="{{ route('admin.permissions.index') }}" class="m-nav__link">
      <span class="m-nav__link-text">Permissions</span>
    </a>
  </li>
  <li class="m-nav__separator">
    -
  </li>
  <li class="m-nav__item">
    <a href="#" class="m-nav__link">
      <span class="m-nav__link-text">Create</span>
    </a>
  </li>
@endsection

@section('content')
  <portlet-content header="Module" subheader="Create" isForm="true">
    <template slot="body">
      <permission-form inline-template method="post"  url="{{ route('admin.permissions.store') }}">
        @include('admin.modules.permission.partials.form')
      </permission-form>
      </template>
    </portlet-content>
@endsection

resources/views/admin/modules/permission/edit.blade.php
@extends('admin.layouts.main')

@section('title', 'Edit Permission')

@section('breadcrumb')
  <li class="m-nav__item">
    <a href="{{ route('admin.permissions.index') }}" class="m-nav__link">
      <span class="m-nav__link-text">Permissions</span>
    </a>
  </li>
  <li class="m-nav__separator">
    -
  </li>
  <li class="m-nav__item">
    <a href="#" class="m-nav__link">
      <span class="m-nav__link-text">Edit</span>
    </a>
  </li>
@endsection

@section('content')
  <permission-form inline-template
                   method="put"
                   permission="{{ json_encode($permission) }}"
                   redirecturl="{{ route('admin.permissions.index') }}"
                   url="{{ route('admin.permissions.update', $permission->id) }}">
    <portlet-content header="Permission" subheader="Edit" isForm="true">
      <template slot="body">
        @include('admin.modules.permission.partials.form')
      </template>
    </portlet-content>
  </permission-form>
@endsection

resources/views/admin/modules/permission/index.blade.php
@extends('admin.layouts.main')

@section('title', 'Permissions')

@section('breadcrumb')
  <li class="m-nav__item">
    <a href="{{ route('admin.permissions.index') }}" class="m-nav__link">
      <span class="m-nav__link-text">Permissions</span>
    </a>
  </li>
  <li class="m-nav__separator">
    -
  </li>
  <li class="m-nav__item">
    <a href="#" class="m-nav__link">
      <span class="m-nav__link-text">List</span>
    </a>
  </li>
@endsection

@section('content')
  <portlet-content header="Permissions" subheader="List" isForm="false">
    <template slot="action_button">
      <div>
        <a href="{{ route('admin.permissions.create') }}">
          <button
              class="btn btn-outline-info m-btn m-btn--icon m-btn--icon-only m-btn--custom m-btn--pill m-btn--air"
              title="Add new Permission"
              data-toggle="tooltip"
          >
            <i class="fa fa-plus"></i>
          </button>
        </a>
      </div>
    </template>
    <template slot="body">
      <div style="padding: 10px;">
        <vue-table
            source="{{ route('admin.permissions.table') }}"
            :columns="['name', 'title', 'action']"
        ></vue-table>
      </div>
    </template>
  </portlet-content>
@endsection

resources/views/admin/modules/users/create.blade.php
@extends('admin.layouts.main')

@section('title', 'Users List')

@section('breadcrumb')
    <li class="m-nav__item">
        <a href="{{ route('admin.users.index') }}" class="m-nav__link">
            <span class="m-nav__link-text">Users</span>
        </a>
    </li>
    <li class="m-nav__separator">
        -
    </li>
    <li class="m-nav__item">
        <a href="#" class="m-nav__link">
            <span class="m-nav__link-text">Create</span>
        </a>
    </li>
@endsection

@section('content')
    {{--send further props from this create user component--}}
    <create-user inline-template url="{{ route('admin.users.store') }}">
        <portlet-content header="Users" subheader="Create" isForm="true">
            <template slot="body">
                <div>
                    <div :class="{'loading': formSubmitting, 'wrapper': formSubmitting}">
                        <!--begin::Form-->
                        <form class="m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed"
                              @submit.prevent="submit">
                            <div class="m-portlet__body" style="padding: inherit;">
                                <div class="form-group m-form__group row">
                                    <div class="col-lg-6">
                                        <label class="required">First Name</label>
                                        <input type="text" name="full_name.first_name"
                                               :class="{ 'input-error' : form.errors.has('full_name.first_name'), 'form-control': loaded }"
                                               placeholder="First Name"
                                               v-model="values.full_name.first_name">
                                        <span class="m-form__help danger"
                                              v-if="form.errors.has('full_name.first_name')"
                                              v-text="form.errors.get('full_name.first_name')"></span>
                                    </div>
                                    <div class="col-lg-6">
                                        <label class="required">Last Name</label>
                                        <input type="text" name="full_name.last_name"
                                               :class="{ 'input-error' : form.errors.has('full_name.last_name'), 'form-control': loaded }"
                                               placeholder="Last Name" v-model="values.full_name.last_name">
                                        <span class="m-form__help danger"
                                              v-if="form.errors.has('full_name.last_name')"
                                              v-text="form.errors.get('full_name.last_name')"></span>
                                    </div>
                                </div>

                                <div class="form-group m-form__group row">
                                    <div class="col-lg-6">
                                        <label class="required">Email</label>
                                        <input type="text" name="email"
                                               :class="{ 'input-error' : form.errors.has('email'), 'form-control': loaded }"
                                               placeholder="Email"
                                               v-model="values.email">
                                        <span class="m-form__help danger"
                                              v-if="form.errors.has('email')"
                                              v-text="form.errors.get('email')"></span>
                                    </div>
                                    <div class="col-lg-6">
                                        <label class="required" for="gender">Username</label>
                                        <input type="text" name="username"
                                               :class="{ 'input-error' : form.errors.has('username'), 'form-control': loaded }"
                                               placeholder="Username"
                                               v-model="values.username">
                                        <span class="m-form__help danger"
                                              v-if="form.errors.has('username')"
                                              v-text="form.errors.get('username')"></span>
                                    </div>
                                </div>


                                <div class="form-group m-form__group row">
                                    <div class="col-lg-6">
                                        <button class="btn btn-primary">Submit</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <!--end::Form-->
                    </div>
                {{--</div>--}}
            </template>
        </portlet-content>
    </create-user>
@endsection

resources/views/admin/modules/users/edit.blade.php
@extends('admin.layouts.main')

@section('title', 'User Edit')

@section('breadcrumb')
    <li class="m-nav__item">
        <a href="{{ route('admin.users.index') }}" class="m-nav__link">
            <span class="m-nav__link-text">Users</span>
        </a>
    </li>
    <li class="m-nav__separator">
        -
    </li>
    <li class="m-nav__item">
        <a href="#" class="m-nav__link">
            <span class="m-nav__link-text">Create</span>
        </a>
    </li>
@endsection

@section('content')
    {{--send further props from this create user component--}}
    <create-user inline-template url="{{ route('admin.users.update', $user->id) }}" method="patch"
                 user="{{ json_encode($user) }}">
        <portlet-content header="Users" subheader="Create" isForm="true">
            <template slot="body">
                <div>
                    <div :class="{'loading': formSubmitting, 'wrapper': formSubmitting}">
                        <!--begin::Form-->
                        <form class="m-form m-form--fit m-form--label-align-right m-form--group-seperator-dashed"
                              @submit.prevent="submit">
                            <div class="m-portlet__body" style="padding: inherit;">
                                <div class="form-group m-form__group row">
                                    <div class="col-lg-6">
                                        <label class="required">First Name</label>
                                        <input type="text" name="full_name.first_name"
                                               :class="{ 'input-error' : form.errors.has('full_name.first_name'), 'form-control': loaded }"
                                               placeholder="First Name"
                                               v-model="values.full_name.first_name">
                                        <span class="m-form__help danger"
                                              v-if="form.errors.has('full_name.first_name')"
                                              v-text="form.errors.get('full_name.first_name')"></span>
                                    </div>
                                    <div class="col-lg-6">
                                        <label class="required">Last Name</label>
                                        <input type="text" name="full_name.last_name"
                                               :class="{ 'input-error' : form.errors.has('full_name.last_name'), 'form-control': loaded }"
                                               placeholder="Last Name" v-model="values.full_name.last_name">
                                        <span class="m-form__help danger"
                                              v-if="form.errors.has('full_name.last_name')"
                                              v-text="form.errors.get('full_name.last_name')"></span>
                                    </div>
                                </div>

                                <div class="form-group m-form__group row">
                                    <div class="col-lg-6">
                                        <label class="required">Email</label>
                                        <input type="text" name="email"
                                               :class="{ 'input-error' : form.errors.has('email'), 'form-control': loaded }"
                                               placeholder="Email"
                                               v-model="values.email">
                                        <span class="m-form__help danger"
                                              v-if="form.errors.has('email')"
                                              v-text="form.errors.get('email')"></span>
                                    </div>
                                    <div class="col-lg-6">
                                        <label class="required" for="gender">Username</label>
                                        <input type="text" name="username"
                                               :class="{ 'input-error' : form.errors.has('username'), 'form-control': loaded }"
                                               placeholder="Username"
                                               v-model="values.username">
                                        <span class="m-form__help danger"
                                              v-if="form.errors.has('username')"
                                              v-text="form.errors.get('username')"></span>
                                    </div>
                                </div>


                                <div class="form-group m-form__group row">
                                    <div class="col-lg-6">
                                        <button class="btn btn-primary">Submit</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <!--end::Form-->
                    </div>
                {{--</div>--}}
            </template>
        </portlet-content>
    </create-user>
@endsection

resources/views/admin/modules/users/show.blade.php
@extends('admin.layouts.main')

@section('title', 'Users Details')

@section('breadcrumb')
    <li class="m-nav__item">
        <a href="{{ route('admin.users.index') }}" class="m-nav__link">
            <span class="m-nav__link-text">Users</span>
        </a>
    </li>
    <li class="m-nav__separator">
        -
    </li>
    <li class="m-nav__item">
        <a href="{{ route('admin.users.show', $user->id) }}" class="m-nav__link">
            <span class="m-nav__link-text">{{ $user->formatted_full_name }}</span>
        </a>
    </li>
@endsection

@section('content')
    <portlet-content header="User" subheader="Details">
        <template slot="action_button">
            <delete-button
                    submiturl="{{ route('admin.users.change.status', [$user->id, $buttonDetails['change_action']]) }}"
                    title="{{ $buttonDetails['title'] }}"
                    swaltitle="Are you sure ?"
                    swalsuccesstitle="{{ $buttonDetails['success_message'] }}"
                    itagclassname="{{ $buttonDetails['icon'] }}"
                    method="patch"
                    redirecturl="{{ route('admin.users.show', [$user->id]) }}"
            ></delete-button>
            <edit-button
                    url="{{ route('admin.users.edit', $user->id) }}"
                    title="Edit User Details"
            >
            </edit-button>
        </template>
        <template slot="body">
            <div class="row">
                @include('admin.modules.users.partials.details')
            </div>
        </template>
    </portlet-content>
@endsection